[{assign var="prefix" value=false}]
[{* if !$oxcmp_user *}] [{* warum habe ich das gemacht? *}]
[{include file="form/inc/input.tpl" _label="EMAIL_ADDRESS" _field="oxuser__oxusername" _type="email" name="lgn_usr" value=$oView->getActiveUsername() _req="required"}]
[{if $oView->getLoginOption() != 1}]
   [{include file="form/inc/input.tpl" _label="PASSWORD" _field="oxuser__oxpassword" _type="password" name="lgn_pwd" value="" _req="required"}]
   [{include file="form/inc/input.tpl" _label="CONFIRM_PASSWORD" _field="oxuser__oxusername" _type="password" name="lgn_pwd2" value="" _req="required"}]
[{/if}]
[{* /if *}]
[{include file="form/fieldset/order_newsletter.tpl" blSubscribeNews=true}]